/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciadeturismo.Vistas;

/**
 *
 * @author Asus
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fArchivo = new javax.swing.JMenu();
        jsalir = new javax.swing.JMenuItem();
        fCliente = new javax.swing.JMenu();
        jFormCliente = new javax.swing.JMenuItem();
        fPaquete = new javax.swing.JMenu();
        jFormPaquete = new javax.swing.JMenuItem();
        fAlojamiento = new javax.swing.JMenu();
        jTipoAlojamiento = new javax.swing.JMenuItem();
        fTraslado = new javax.swing.JMenu();
        jFormTraslado = new javax.swing.JMenuItem();
        fCompra = new javax.swing.JMenu();
        jIngresoCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        fArchivo.setText("Archivo");

        jsalir.setText("Salir");
        jsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalirActionPerformed(evt);
            }
        });
        fArchivo.add(jsalir);

        jMenuBar1.add(fArchivo);

        fCliente.setText("Cliente");

        jFormCliente.setText("Formulario Cliente");
        jFormCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormClienteActionPerformed(evt);
            }
        });
        fCliente.add(jFormCliente);

        jMenuBar1.add(fCliente);

        fPaquete.setText("Paquete");

        jFormPaquete.setText("Formulario Paquete");
        jFormPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormPaqueteActionPerformed(evt);
            }
        });
        fPaquete.add(jFormPaquete);

        jMenuBar1.add(fPaquete);

        fAlojamiento.setText("Alojamiento");

        jTipoAlojamiento.setText("Tipos de Alojamientos ");
        fAlojamiento.add(jTipoAlojamiento);

        jMenuBar1.add(fAlojamiento);

        fTraslado.setText("Traslado");

        jFormTraslado.setText("Formulario Traslado");
        fTraslado.add(jFormTraslado);

        jMenuBar1.add(fTraslado);

        fCompra.setText("Compra");

        jIngresoCompra.setText("Ingresar Compra");
        fCompra.add(jIngresoCompra);

        jMenuBar1.add(fCompra);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormClienteActionPerformed

    private void jsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsalirActionPerformed

    private void jFormPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormPaqueteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fAlojamiento;
    private javax.swing.JMenu fArchivo;
    private javax.swing.JMenu fCliente;
    private javax.swing.JMenu fCompra;
    private javax.swing.JMenu fPaquete;
    private javax.swing.JMenu fTraslado;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jFormCliente;
    private javax.swing.JMenuItem jFormPaquete;
    private javax.swing.JMenuItem jFormTraslado;
    private javax.swing.JMenuItem jIngresoCompra;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jTipoAlojamiento;
    private javax.swing.JMenuItem jsalir;
    // End of variables declaration//GEN-END:variables
}
